# Change these first
owner: emothek # Your GitHub organization or username, where this repository lives
repo: lets_upptime # The name of this repository

sites:
  - name: Letsact landing page
    url: https://letsact.de
  - name: Lets landing page
    url: https://joinlets.de
  - name: Joinlets
    url: https://app.joinlets.de
  - name: Unsekinder
    url: https://undekinder.joinlets.de
  - name: FondsFinanz
    url: https://fondsfinanz.joinlets.de
  - name: Die Bayerische
    url: https://diebayerische.joinlets.de
  - name: New Letsact web 2
    url: https://app.letsact.de
  - name: Letsact Org tool
    url: https://org.letsact.de
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: lets_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Lets Up-time monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
